name: Main

on:
    push:
        paths-ignore:

jobs:

    ci:
        runs-on: windows-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
            
            - uses: actions/setup-dotnet@v1
              with:
                dotnet-version: '3.1.100'
            
            - name: Build
              run: dotnet build
            
            - name: Test
              run: dotnet test

            - name: Release
              uses: cycjimmy/semantic-release-action@v2
              with:
                semantic_version: 17
                extra_plugins: |
                  semantic-release-plugin-csproj
                  @semantic-release/exec
                  @semantic-release/changelog
                  @semantic-release/git
                branch: master
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 